import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";
import Rightnav from "@/components/Rightnav";
import { Toaster } from "@/components/ui/sonner"
import CallListener from "@/components/CallListener";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Echo",
  description: "Generated by Ahmet Selim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CallListener />
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-screen h-screen overflow-hidden flex flex-col bg-linear-to-br from-indigo-500 via-purple-500 to-pink-500">
            <header className="w-full h-14 px-2 pt-2 relative z-50">
              <div className="w-full h-full bg-background/95 backdrop-blur-sm rounded-t-xl md:rounded-xl shadow-lg">
                <Header />
              </div>
            </header>
            <div className="w-full flex-1 flex gap-2 mt-2 p-2 pt-0 overflow-hidden">
              <nav className="h-full hidden md:flex md:flex-col w-fit">
                <div className="h-full bg-background/95 backdrop-blur-sm rounded-xl shadow-lg overflow-y-auto no-scrollbar">
                  <Navbar />
                </div>
              </nav>
              <div className="flex-1 flex gap-2 min-w-0 overflow-hidden">
                <main className="flex-1 bg-background/95 backdrop-blur-sm rounded-xl shadow-lg overflow-hidden">
                  {children}
                </main>
                <aside className="h-full hidden lg:flex lg:flex-col w-fit">
                  <div className="h-full bg-background/95 backdrop-blur-sm rounded-xl shadow-lg overflow-y-auto custom-scrollbar">
                    <Rightnav />
                  </div>
                </aside>
              </div>
            </div>
          </div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}