import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider"
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Echo",
  description: "Generated by Ahmet Selim",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="w-screen h-screen overflow-hidden flex flex-col bg-linear-to-tr from-fuchsia-800 to-indigo-800">
            <header className="w-screen h-14">
              <Header />
            </header>
            <div className="w-full h-[calc(100vh-56px)] flex">
              <nav className="h-full hidden md:w-fit md:flex md:flex-col items-center justify-start overflow-y-scroll">
                <Navbar />
              </nav>
              <div className="flex-1 flex pb-2 pr-2 gap-2">
                <main className="flex-1 bg-background md:rounded-xl">
                  {children}
                </main>
                <div className="h-full w-72 bg-card rounded-lg">

                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
